"""Regenerate backend/services/translation_preview_samples.py.

The job-creation "translated lyrics" preview renders sample lyrics with their
translation beneath. Translations are generated once with the production
translation service and committed, so the preview never calls the LLM.

    GOOGLE_CLOUD_PROJECT=nomadkaraoke python backend/scripts/generate_translation_preview_samples.py
"""
import os
import pprint
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from backend.services.lyrics_translation import TRANSLATION_LANGUAGES, LyricsTranslationService  # noqa: E402
from backend.services.theme_preview_service import DEFAULT_SAMPLE_LYRICS  # noqa: E402

# Shown instead of the English sample when the target language is English
SPANISH_SAMPLE_LYRICS = [
    "Cada noche canto sin parar",
    "Se apagan las luces, es mi lugar",
    "Tomo el micrófono y subo al escenario",
    "Doy la vuelta a la página otra vez",
]


class _NoCache:
    def file_exists(self, path):
        return False

    def upload_json(self, path, data):
        pass


def main():
    service = LyricsTranslationService(storage=_NoCache())
    samples = {}
    for code in TRANSLATION_LANGUAGES:
        source = SPANISH_SAMPLE_LYRICS if code == "en" else DEFAULT_SAMPLE_LYRICS
        samples[code] = {"lyrics": source, "translations": service.translate_lines(source, code)}
        print(code, samples[code]["translations"][0], file=sys.stderr)
    out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "services", "translation_preview_samples.py")
    with open(out, "w", encoding="utf-8") as f:
        f.write('"""Sample lyrics + translations for the translated-lyrics preview.\n\n')
        f.write("Generated by backend/scripts/generate_translation_preview_samples.py; don't edit by hand.\n")
        f.write('"""\n\n')
        f.write("SAMPLES = " + pprint.pformat(samples, width=110, sort_dicts=False) + "\n")


if __name__ == "__main__":
    main()
