"""
Utilities for identifying test data and internal accounts.

Test data is generated by automated E2E tests and should be filterable
in admin dashboards to show only real user data by default.

Internal accounts belong to team members and should be excluded from
abuse investigation views.
"""

# Email domains used by automated testing frameworks
TEST_EMAIL_DOMAINS = [
    "inbox.testmail.app",  # Used by E2E happy path tests (ephemeral throwaway users)
]

# Specific internal accounts that are only ever used by automated tests.
# These live on the internal nomadkaraoke.com domain (so they'd otherwise pass
# is_internal_email, not is_test_email), but every job they create is E2E test
# data. Listed here so admin dashboards' exclude_test filter hides their jobs.
# e2e-test-runner is the persistent account the CI post-deploy canary and daily
# E2E workflows impersonate; without this entry its piri/dog jobs leak into the
# admin "My Jobs" view.
TEST_EMAIL_ADDRESSES = [
    "e2e-test-runner@nomadkaraoke.com",
]

# Email domains belonging to internal team members
INTERNAL_EMAIL_DOMAINS = [
    "nomadkaraoke.com",  # Team accounts
    "beveridge.uk",  # Founder's personal domain
]


def is_test_email(email: str) -> bool:
    """
    Check if an email address belongs to automated test data.

    Args:
        email: Email address to check

    Returns:
        True if the email matches a test email domain pattern or is a known
        automated-test account
    """
    if not email:
        return False
    email_lower = email.lower()
    if email_lower in TEST_EMAIL_ADDRESSES:
        return True
    return any(email_lower.endswith(f"@{domain}") for domain in TEST_EMAIL_DOMAINS)


def is_internal_email(email: str) -> bool:
    """Check if an email address belongs to an internal team member."""
    if not email:
        return False
    email_lower = email.lower()
    return any(email_lower.endswith(f"@{domain}") for domain in INTERNAL_EMAIL_DOMAINS)


def is_internal_or_test_email(email: str) -> bool:
    """Check if an email is internal or automated test data."""
    return is_test_email(email) or is_internal_email(email)
