"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { useLocale, useTranslations } from "next-intl"
import { Languages, Loader2 } from "lucide-react"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { routing } from "@/i18n/routing"
import { api } from "@/lib/api"

/** Languages a job's lyrics can be translated into (same set as the UI locales). */
export const TRANSLATION_LANGUAGES: readonly string[] = routing.locales

interface TranslatedLyricsOptionProps {
  /** Selected language code, or null when translated lyrics are off. */
  value: string | null
  onChange: (value: string | null) => void
  disabled?: boolean
}

/**
 * Opt-in for a karaoke video that shows an AI translation of each lyric line in
 * smaller text beneath the synced lyrics. The translation is generated by the
 * backend after lyrics review, so it isn't editable here. Shows a real rendered
 * sample frame (default theme) for the chosen language.
 */
export function TranslatedLyricsOption({ value, onChange, disabled }: TranslatedLyricsOptionProps) {
  const t = useTranslations("jobFlow")
  const uiLocale = useLocale()
  const enabled = value !== null

  const languages = useMemo(() => {
    let names: Intl.DisplayNames | null = null
    try {
      names = new Intl.DisplayNames([uiLocale], { type: "language" })
    } catch {
      names = null
    }
    return TRANSLATION_LANGUAGES
      .map((code) => ({ code, label: names?.of(code) ?? code }))
      .sort((a, b) => a.label.localeCompare(b.label, uiLocale))
  }, [uiLocale])

  const defaultLanguage = TRANSLATION_LANGUAGES.includes(uiLocale) ? uiLocale : "en"
  const languageLabel = (code: string) => languages.find((l) => l.code === code)?.label ?? code

  // Preview frames cached per language. Responses are stored under the language
  // they were requested for, so a slow response for a previously selected
  // language never replaces the preview of the current one.
  const [previews, setPreviews] = useState<Record<string, string>>({})
  const [failed, setFailed] = useState<Record<string, boolean>>({})
  const inFlight = useRef<Set<string>>(new Set())
  const mounted = useRef(true)
  useEffect(() => {
    mounted.current = true
    return () => { mounted.current = false }
  }, [])

  useEffect(() => {
    if (!value || previews[value] || failed[value] || inFlight.current.has(value)) return
    const language = value
    inFlight.current.add(language)
    api.getTranslationPreview(language)
      .then((res) => {
        if (mounted.current) setPreviews((prev) => ({ ...prev, [language]: res.image }))
      })
      .catch(() => {
        if (mounted.current) setFailed((prev) => ({ ...prev, [language]: true }))
      })
      .finally(() => {
        inFlight.current.delete(language)
      })
  }, [value, previews, failed])

  function handleToggle(checked: boolean) {
    onChange(checked ? defaultLanguage : null)
  }

  function clearFailure(code: string) {
    setFailed((prev) => {
      const next = { ...prev }
      delete next[code]
      return next
    })
  }

  function handleLanguageChange(code: string) {
    // Selecting a language whose preview failed retries it.
    if (failed[code]) clearFailure(code)
    onChange(code)
  }

  const previewImage = value ? previews[value] : undefined
  const previewFailed = value ? !!failed[value] : false

  return (
    <div
      className="space-y-4 rounded-lg border p-4"
      style={{ borderColor: 'var(--card-border)', backgroundColor: 'rgba(255,255,255,0.02)' }}
      data-testid="translated-lyrics-option"
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <Languages className="w-4 h-4" style={{ color: 'var(--brand-pink)' }} />
            <Label htmlFor="translated-lyrics-toggle" className="text-sm font-semibold" style={{ color: 'var(--text)' }}>
              {t('translatedLyricsToggle')}
            </Label>
          </div>
          <p className="text-[10px] mt-1" style={{ color: 'var(--text-muted)' }}>
            {t('translatedLyricsToggleHint')}
          </p>
        </div>
        <Switch
          id="translated-lyrics-toggle"
          checked={enabled}
          onCheckedChange={handleToggle}
          disabled={disabled}
        />
      </div>

      {enabled && value && (
        <div className="space-y-3">
          <div className="space-y-1.5">
            <Label htmlFor="translated-lyrics-language" className="text-xs" style={{ color: 'var(--text-muted)' }}>
              {t('translatedLyricsLanguageLabel')}
            </Label>
            <select
              id="translated-lyrics-language"
              value={value}
              onChange={(e) => handleLanguageChange(e.target.value)}
              disabled={disabled}
              className="w-full h-9 rounded-md border px-2 text-sm"
              style={{ backgroundColor: 'var(--secondary)', borderColor: 'var(--card-border)', color: 'var(--text)' }}
            >
              {languages.map((lang) => (
                <option key={lang.code} value={lang.code}>{lang.label}</option>
              ))}
            </select>
            <p className="text-[10px]" style={{ color: 'var(--text-muted)' }}>
              {t('translatedLyricsHint', { language: languageLabel(value) })}
            </p>
          </div>

          <div
            className="relative w-full aspect-video overflow-hidden rounded-md border"
            style={{ borderColor: 'var(--card-border)', backgroundColor: 'var(--secondary)' }}
          >
            {previewImage ? (
              /* eslint-disable-next-line @next/next/no-img-element */
              <img
                src={previewImage}
                alt={t('translatedLyricsPreviewAlt', { language: languageLabel(value) })}
                className="w-full h-full object-contain"
                data-testid="translated-lyrics-preview"
              />
            ) : previewFailed ? (
              <div className="absolute inset-0 flex items-center justify-center p-4 text-center">
                <div className="space-y-2">
                  <p className="text-xs" style={{ color: 'var(--text-muted)' }} data-testid="translated-lyrics-preview-error">
                    {t('translatedLyricsPreviewError')}
                  </p>
                  <button
                    type="button"
                    onClick={() => clearFailure(value)}
                    disabled={disabled}
                    className="text-xs underline"
                    style={{ color: 'var(--brand-pink)' }}
                    data-testid="translated-lyrics-preview-retry"
                  >
                    {t('translatedLyricsPreviewRetry')}
                  </button>
                </div>
              </div>
            ) : (
              <div
                className="absolute inset-0 flex flex-col items-center justify-center gap-2 animate-pulse"
                data-testid="translated-lyrics-preview-loading"
              >
                <Loader2 className="w-5 h-5 animate-spin" style={{ color: 'var(--text-muted)' }} />
                <p className="text-xs" style={{ color: 'var(--text-muted)' }}>
                  {t('translatedLyricsPreviewLoading')}
                </p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
