"""Render generated karaoke ASS with real ffmpeg/libass and measure the highlight.

Used by test_ass_render_highlight.py to verify *how lyrics actually render*, not just
what tags we emit: which edge the highlight starts from, which way it sweeps within
and across words, where the lead-in lands, and whether libass found glyphs for
every character.

The ASS is generated by the real SubtitlesGenerator with a pure-colour palette so each
pixel can be classified deterministically:

    sung (PrimaryColour)      -> pure green
    unsung (SecondaryColour)  -> pure magenta
    lead-in rectangle         -> pure cyan
    background                -> black

Outline/shadow are disabled so antialiased edges only blend a colour with black.
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

from karaoke_gen.lyrics_transcriber.output.subtitles import SubtitlesGenerator
from karaoke_gen.lyrics_transcriber.types import LyricsSegment, Word
from karaoke_gen.style_loader import DEFAULT_KARAOKE_STYLE

WIDTH, HEIGHT = 1280, 720
FPS = 25
FONT_SIZE = 70
RESOURCES_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "karaoke_gen", "resources")
THEME_FONT_PATH = os.path.abspath(os.path.join(RESOURCES_DIR, "AvenirNext-Bold.ttf"))
THEME_FONT_NAME = "Avenir Next"

# Word timing used by every sample line: WORD_START_S + i * WORD_STEP_S, lasting WORD_DUR_S.
LINE_START_S = 4.0
WORD_STEP_S = 1.0
WORD_DUR_S = 0.9

# Override to render with a specific binary, e.g. the static johnvansickle build prod uses
# (see scripts/run-render-tests-linux.sh).
FFMPEG = os.environ.get("KARAOKE_RENDER_TEST_FFMPEG", "ffmpeg")

# libass log line emitted when no installed font has a glyph (it then draws nothing).
MISSING_GLYPH_RE = re.compile(r"failed to find any fallback with glyph (0x[0-9A-Fa-f]+)")


def ffmpeg_has_libass() -> bool:
    if not shutil.which(FFMPEG):
        return False
    out = subprocess.run([FFMPEG, "-hide_banner", "-filters"], capture_output=True, text=True).stdout
    return re.search(r"^\s*\S*\s+ass\s", out, re.MULTILINE) is not None


def make_segment(words: Sequence[str], start: float = LINE_START_S, singers: Optional[Sequence[int]] = None,
                 segment_singer: Optional[int] = None, seg_id: str = "s1") -> LyricsSegment:
    word_objs = []
    for i, text in enumerate(words):
        ws = start + i * WORD_STEP_S
        word_objs.append(Word(
            id=f"{seg_id}w{i}", text=text, start_time=ws, end_time=ws + WORD_DUR_S,
            singer=singers[i] if singers else None,
        ))
    return LyricsSegment(
        id=seg_id, text=" ".join(words), words=word_objs,
        start_time=word_objs[0].start_time, end_time=word_objs[-1].end_time,
        singer=segment_singer,
    )


def word_mid(i: int, frac: float = 0.5) -> float:
    """Timestamp ``frac`` of the way through word ``i`` of a make_segment line."""
    return LINE_START_S + i * WORD_STEP_S + frac * WORD_DUR_S


def karaoke_style(**overrides) -> dict:
    style = dict(DEFAULT_KARAOKE_STYLE)
    style.update({
        "font": THEME_FONT_NAME,
        "font_path": THEME_FONT_PATH,
        "primary_color": "0, 255, 0, 255",      # sung
        "secondary_color": "255, 0, 255, 255",  # unsung
        "outline_color": "0, 0, 0, 255",
        "back_color": "0, 0, 0, 0",
        "outline": 0,
        "shadow": 0,
        "top_padding": 150,
        "lead_in_color": "0, 255, 255",
        "lead_in_opacity_percent": 100,
        "lead_in_outline_thickness": 0,
    })
    # Duets: make every singer render with the same palette so the pixel classifier
    # still works while the {\1c..}/{\r} override path is exercised.
    style["singers"] = {k: {"primary_color": style["primary_color"], "secondary_color": style["secondary_color"],
                            "outline_color": style["outline_color"]} for k in ("1", "2", "both")}
    style.update(overrides)
    return style


def generate_ass(tmp_path, segments: List[LyricsSegment], is_duet: bool = False, **style_overrides) -> str:
    gen = SubtitlesGenerator(
        output_dir=str(tmp_path),
        video_resolution=(WIDTH, HEIGHT),
        font_size=FONT_SIZE,
        line_height=FONT_SIZE + 20,
        styles={"karaoke": karaoke_style(**style_overrides)},
        is_duet=is_duet,
    )
    return gen.generate_ass(segments, "render-test", audio_filepath=None)


@dataclass
class RenderResult:
    frames: Dict[float, np.ndarray]  # timestamp -> HxWx3 uint8
    log: str

    @property
    def missing_glyphs(self) -> List[str]:
        return MISSING_GLYPH_RE.findall(self.log)


def render_frames(ass_path: str, times: Sequence[float]) -> RenderResult:
    """Render the ASS on black with libass and return the frames at ``times``."""
    frame_numbers = sorted({int(round(t * FPS)) for t in times})
    duration = frame_numbers[-1] / FPS + 0.5
    select = "+".join(f"eq(n\\,{n})" for n in frame_numbers)

    def esc(p: str) -> str:
        return p.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'")

    vf = f"ass='{esc(ass_path)}':fontsdir='{esc(os.path.dirname(THEME_FONT_PATH))}',select='{select}'"
    cmd = [
        FFMPEG, "-hide_banner", "-loglevel", "info", "-nostdin",
        "-f", "lavfi", "-i", f"color=c=black:s={WIDTH}x{HEIGHT}:r={FPS}:d={duration}",
        "-vf", vf, "-fps_mode", "passthrough", "-f", "rawvideo", "-pix_fmt", "rgb24", "pipe:1",
    ]
    proc = subprocess.run(cmd, capture_output=True, timeout=120)
    log = proc.stderr.decode("utf-8", "replace")
    if proc.returncode != 0:
        raise RuntimeError(f"ffmpeg failed ({proc.returncode}):\n{log[-3000:]}")
    raw = np.frombuffer(proc.stdout, dtype=np.uint8)
    frames = raw.reshape(-1, HEIGHT, WIDTH, 3)
    assert len(frames) == len(frame_numbers), f"expected {len(frame_numbers)} frames, got {len(frames)}"
    by_number = dict(zip(frame_numbers, frames))
    return RenderResult(frames={t: by_number[int(round(t * FPS))] for t in times}, log=log)


# ---- pixel classification -------------------------------------------------------

def _masks(frame: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    f = frame.astype(np.int16)
    r, g, b = f[..., 0], f[..., 1], f[..., 2]
    bright = np.maximum(np.maximum(r, g), b) > 90
    sung = bright & (g > r + 60) & (g > b + 60)
    unsung = bright & (r > g + 60) & (b > g + 60)
    lead_in = bright & (g > r + 60) & (b > r + 60)
    return sung, unsung, lead_in


@dataclass
class LineMeasure:
    """Horizontal extents of one rendered lyric line (pixel columns)."""
    left: int
    right: int
    top: int
    bottom: int
    sung_cols: np.ndarray    # sorted x columns containing sung pixels
    unsung_cols: np.ndarray  # sorted x columns containing unsung pixels

    @property
    def center_x(self) -> float:
        return (self.left + self.right) / 2

    @property
    def sung_fraction(self) -> float:
        total = len(self.sung_cols) + len(self.unsung_cols)
        return len(self.sung_cols) / total if total else 0.0


def lyric_lines(frame: np.ndarray) -> List[LineMeasure]:
    """Split the lyric text (sung + unsung pixels) into horizontal line bands, top to bottom."""
    sung, unsung, _ = _masks(frame)
    text = sung | unsung
    rows = np.where(text.any(axis=1))[0]
    if len(rows) == 0:
        return []
    bands, start, prev = [], rows[0], rows[0]
    for y in rows[1:]:
        if y - prev > 8:
            bands.append((start, prev))
            start = y
        prev = y
    bands.append((start, prev))
    lines = []
    for top, bottom in bands:
        band = slice(top, bottom + 1)
        cols = np.where(text[band].any(axis=0))[0]
        lines.append(LineMeasure(
            left=int(cols.min()), right=int(cols.max()), top=int(top), bottom=int(bottom),
            sung_cols=np.where(sung[band].any(axis=0))[0],
            unsung_cols=np.where(unsung[band].any(axis=0))[0],
        ))
    return lines


def lead_in_box(frame: np.ndarray) -> Optional[Tuple[int, int, int, int]]:
    """(left, top, right, bottom) of the lead-in rectangle, or None if not visible."""
    _, _, lead = _masks(frame)
    ys, xs = np.where(lead)
    if len(xs) < 20:
        return None
    return int(xs.min()), int(ys.min()), int(xs.max()), int(ys.max())
