config:
  gcp:project: nomadkaraoke
  gcp:region: us-central1
  karaoke-gen-infrastructure:backupEncryptionPubkey: 1e966a0693d4ab12f5ef570dd60b35137ec12c42cc12424e13e8c1e8e2dbc914
  edge:originSecret:
    secure: AAABAPgh/fn2A5urhLq8nN0zegTSPD4073aN3P+2Jqyg+xexxpq+QMWVfZbYOxfa6WpFXLtCFfVv/TlpjL+gmJ9xOtyBdWXF+g9fu29Cf64RJxGRKLo34eMMZ3MGguKx
  cloudflare:apiToken:
    secure: AAABAGX6zpucCw1NvaYSCCg5YDFVuf5Thw+HL8njNfGiLoT8qpY9UhleyJy6rsnTwFo42AKUntWTK2hCAZq7VN55vBKiuHZa3NqJ37/yjpoz4EAssA==
  edge:enabled: "true"
